vial keychron k8 pro iso/rgb support
adophoxia/vial-qmk pull request #6
Opened 2023-12-02 12:57 UTC by cloonix

Added vial support for Keychron K8 Pro ISO/RGB layout based on adophoxia/vial-qmk/keychron-bluetooth-PR pull request which makes Bluetooth available for new Keychron BT keyboards.

2023-12-02 23:45 UTC, adophoxia requested changes

2023-12-02 23:45 UTC, adophoxia commented on keyboards/keychron/k8_pro/iso/rgb/keymaps/vial/config.h
> +#define DYNAMIC_KEYMAP_MACRO_COUNT 32
Is there a reason this define is added?

2023-12-02 23:45 UTC, adophoxia commented on keyboards/keychron/k8_pro/iso/rgb/config.h
> +#    define RGB_MATRIX_LED_COUNT (DRIVER_1_LED_COUNT + DRIVER_2_LED_COUNT)
```suggestion
#    define RGB_MATRIX_LED_COUNT 88

2023-12-03 09:29 UTC, cloonix commented on keyboards/keychron/k8_pro/iso/rgb/keymaps/vial/config.h
> +#define DYNAMIC_KEYMAP_MACRO_COUNT 32
Updated code and removed personal customization (macro count)

2023-12-03 09:30 UTC, cloonix commented on keyboards/keychron/k8_pro/iso/rgb/config.h
> +#    define RGB_MATRIX_LED_COUNT (DRIVER_1_LED_COUNT + DRIVER_2_LED_COUNT)
Took my code from the Keychron/qmk_firmware/bluetooth_playground. Couldn't find a reason for that calculation. Removed it.

2023-12-09 02:35 UTC, adophoxia approved these changes
LGTM!

2023-12-09 05:02 UTC, merged